name: flutter_feed_reaction
description: A new Flutter package project to show your reactions in posts/comments.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_portal: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

assets:
  - assets/emojies/
  - assets/lottie/